Mailman/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("main_app.urls")),
    path("", include('django.contrib.auth.urls')),
    path("admin/", admin.site.urls),
]

main_app/urls.py
from django.urls import path
from main_app import views

urlpatterns = [
    path("", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("home/", views.home, name="home"),
    path("package/<int:pkg_id>/", views.package_detail, name="detail"),
    path("profile/", views.profile, name="profile"),
    path("package/", views.package_create, name="package"),
    path("package/<int:pk>/update/", views.PackageUpdate.as_view(), name="package_update"),
    path("package/<int:pk>/delete/", views.PackageDelete.as_view(), name="package_delete"),
    path("package/<int:pkg_id>/assoc_driver/<int:user_id>/", views.assoc_driver, name="assoc_driver"),
]

main_app/models.py
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.db import models

class Package(models.Model):
    origination = models.CharField(max_length=100)
    destination = models.CharField(max_length=100)
    length = models.IntegerField()
    width = models.IntegerField()
    height = models.IntegerField()
    weight = models.IntegerField()
    is_fragile = models.BooleanField()
    destination_length = models.IntegerField(blank=True, null=True)
    cost_of_delivery = models.IntegerField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    users = models.ManyToManyField(User)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pkg_id': self.id})

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    deliveries = models.ForeignKey(Package, on_delete=models.CASCADE, blank=True, null=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

main_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from .models import Package

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class PackageForm(ModelForm):
    class Meta:
        model = Package
        fields = ["origination", "destination", "length", "width", "height", "weight", "is_fragile", "destination_length", "cost_of_delivery", "completed", "users"]

main_app/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from .forms import SignUpForm, PackageForm
from .models import Package

def login(request):
    return render(request, "../templates/registration/login.html")

def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            username = authenticate(username=username, password=raw_password)
            login(request)
            return redirect("/login/")
    else:
        form = SignUpForm()
    return render(request, "registration/signup.html", {"form": form})

@login_required
def home(request):
    packages = Package.objects.all()
    return render(request, "main_app/home.html", { "packages": packages })

@login_required
def profile(request):
    print(request.user)
    packages = Package.objects.filter(users__username = request.user)
    return render(request, "main_app/profile.html", { "packages": packages, "user": request.user })

@login_required
def package_detail(request, pkg_id):
    package = Package.objects.get(id=pkg_id)
    shipper = package.users.first()
    return render(request, "main_app/detail.html", { "package": package, "shipper": shipper })

@login_required
def assoc_driver(request, pkg_id, user_id):
    Package.objects.get(id=pkg_id).users.add(user_id)
    return redirect("/profile/")

@login_required
def package_create(request):
    if request.method == "POST":
        user_id = request.POST["users"]
        user = User.objects.get(id=user_id)
        form = PackageForm(request.POST)
        new_package = form.save(commit=False)
        new_package.save()
        package = Package.objects.get(id=new_package.id)
        package.users.add(user)
        return redirect("/profile/")
    else:
        return render(request, "main_app/package_form.html")

class PackageUpdate(UpdateView):
    model = Package
    fields = ["length", "width", "height", "weight", "is_fragile"]
    success_url = "/profile/"
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class PackageDelete(DeleteView):
    model = Package
    success_url = "/profile/"
<<<<<<< HEAD

def profile(request):
    print(request.user)
    packages=Package.objects.filter(users__username = request.user)
    return render(request, 'main_app/profile.html', { "packages": packages, "user": request.user })

# @login_required
def package_detail(request, pkg_id):
    packages = Package.objects.get(user = request.user)
    return render(request, 'main_app/detail.html', { "packages": packages })


@login_required
def package_detail(request, pkg_id):
    package = Package.objects.get(id=pkg_id)
    return render(request, 'main_app/detail.html', {"package": package})


@login_required
def assoc_driver(request, pkg_id, user_id):
    user = request.user
    Package.objects.get(id=pkg_id).users.add(user_id)
    return redirect('/profile/')
=======
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
>>>>>>> a1830e78870a1f68788bb444d06d5d43862aef6b

main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <!-- <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
        integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
        crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
        integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
        crossorigin=""></script> -->

    <title>Mailman</title>
</head>

<body>
    <header>
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="{% url 'home' %}" class="left" id="header-logo"><img src="../static/images/logored.png"
                                alt="Mailman Logo"></a></li>
                </ul>
                <ul class="nav right">
                    <li><a href="{% url 'home' %}">HOME</a></li>
                    <li><a href="{% url 'profile' %}">PROFILE</a></li>
                    <li><a href="{% url 'login' %}">LOGOUT</a></li>
                </ul>
            </div>
            <hr class="hr-header"/>
        </nav>
    </header>
    <main>
    {% block content %}
    {% endblock %}
    </main>
</body>

</html>

main_app/templates/main_app/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css">
    <!-- <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
        integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
        crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
        integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
        crossorigin=""></script> -->

    <title>Mailman</title>
</head>

<body>    
    <header>
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="{% url 'home' %}" class="left" id="header-logo"><img src="../../static/images/logored.png"
                                alt="Mailman Logo"></a></li>
                </ul>
                <ul class="nav right">
                    <li><a href="{% url 'home' %}">HOME</a></li>
                    <li><a href="{% url 'profile' %}">PROFILE</a></li>
                    <li><a href="{% url 'login' %}">LOGOUT</a></li>
                </ul>
            </div>
            <hr class="hr-header" />
        </nav>
    </header>
    <main>
{% block content %}
        <h1 class="heading">DELIVERY DETAIL</h1>
    <div class="page-container">

        <div id="mapid">map</div>

        <div id="details-container">
            <table class="table detail">
                <tr>
                    <th class="detail-header">Package ID:</th>
                    <td class="details-detail">{{ package.id }}</td>
                </tr>
                <tr>
                    <th class="detail-header">Shipper:</th>
                    <td class="details-detail">{{ shipper }}</td>
                </tr>
                <tr>
                    <th class="detail-header">Origin:</th>
                    <td class="details-detail">{{ package.origination }}</td>
                </tr>
                <tr>
                    <th class="detail-header">Destination:</th>
                    <td class="details-detail">{{ package.destination }}</td>
                </tr>
                <tr>
                    <th class="detail-header">Distance:</th>
                    <td class="details-detail">{{ package.distance }}</td>
                </tr>
            </table>
        </div>
        <div class="button-section">
            <form action="{% url 'assoc_driver' package.id user.id %}" method="post">
                {% csrf_token %}
                <button type="submit">ACCEPT</button>
                <a class="package-button cancel" href="{% url 'home' %}">CANCEL</a>
            </form>
        </div>
    </div>

{% endblock %}
    </main>
</body>

</html>

main_app/templates/main_app/home.html
{% extends 'base.html' %}
{% block content %}

<h1 class="heading">Welcome: {{ user.get_username }}</h1>
<div class="page-container home">
    <div id="user-info">
        <h2>Profile</h2>
        <p class="user-info name">Name:<span class="user-info-cont">{{ user.first_name }} {{ user.last_name }}</span></p>
        <p>E-mail: <span style="margin-left: 1rem; font-size: larger;">{{ user.email }}</span></p>
    
        <!-- profile info and current rating -->
    </div>
    <div id="avail-del">
        <hr>
        <h2 class="heading">Packages for Delivery</h2>
        {% for package in packages %}
    
        {% if package in packages %}
        <div class="flex-column-container">
            <div class="shipments">
                <div class="section-1">
                    <h5 class="sec-1 st">SHIPPING FROM</h5>
                    <h4 class="sec-1 un">{{ package.origination }}</h4>
                </div>
                <div class="section-2">
                    <div class="cities">
                        <div class="circle-container body1">
                            <!-- city first letter -->
                           <span>A</span> 
                        </div>
                        <div class="city">
                            <!-- city -->
                            POINT A
                        </div>
                    </div>
        
                    <div class="dots">● &nbsp; ● &nbsp; ● &nbsp; ●</div>
                            <!-- distance -->
                            
                    <div class="distance"> 
                        {% if package.destination_length > 0 %}
                        <h2>{{ package.destination_length }} mi</h2> 
                        {% else %}
                        <h2>N/A</h2>
                        {% endif %}
                    </div>
        
        
                    <div class="dots">● &nbsp; ● &nbsp; ● &nbsp; ●</div>
        
                    <div class="cities">
                        <div class="circle-container body2">
                            <!-- city first letter -->
                           <span>B</span>
                        </div>
                        <div class="city">
                            <!-- city -->
                            POINT B
                        </div>
                    </div>
                </div>
                <div class="section-4">
                    <h5 class="sec-4 st">DELIVER TO</h5>
                    <h4 class="sec-4 un">{{ package.destination }}</h4>
                </div>
                <div class="section-3">
                    <a class="button small" href="{% url 'detail' package.id %}">DETAILS</a>
                    <a class="button small" href="">ACCEPT</a>
                </div>

            </div>
            {% else %}
            <h4>There are no deliveries available.</h4>
            {% endif %}
            {% endfor %}
            <!-- pull info for created shipments -->
        </div>
    </div>
    
    <div id="newship">
        <button class="button home"><a href="{% url 'package' %}">New Shipment</a></button>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/package_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Cancel Package</h1>

<h4>Are you sure you want to delete the package from <span>{{ object.origination }} going to {{ object.destination }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, cancel Package">
  <a href="{% url 'profile' %}">Nope, I want to keep</a>
</form>
{% endblock %}

main_app/templates/main_app/package_form.html
{% extends 'base.html' %}
{% block content %}
<h1 class="heading">Shipment Info</h1>
<form method="POST" action="">
    {% csrf_token %}
    <div class="page-container">
        <div class="flex-column-container pkg-form">
            <label for="id_origination">Origination:</label><input type="text" name="origination" maxlength="100"
                required="" id="id_origination">
            <label for="id_destination">Destination:</label><input type="text" name="destination" maxlength="100"
                required="" id="id_destination">
            <label for="id_length">Length:</label><input type="number" name="length" required="" id="id-length">
            <label for="id_width">Width:</label><input type="number" name="width" required="" id="id-width">
            <label for="id_height">Height:</label><input type="number" name="height" required="" id="id-height">
            <label for="id_weight">Weight:</label><input type="number" name="weight" required="" id="id-weight">
            <label for="id_is_fragile">Is fragile:</label><input type="checkbox" name="is-fragile" id="id-is-fragile">
            <label for="id_users"></label><select name="users" required="" id="id-users" multiple="">
                <option id="opt-user"value="{{ request.user.id }}" name="logged_user">{{ request.user }}</option>

            </select>

        </div>
        <div id="btn-pkg-container">
            <input class="button landing pkg" type="submit" value="Create">
        </div>
    </div>
</form>


{% endblock %}

main_app/templates/main_app/profile.html
{% extends 'base.html' %}
{% block content %}

<!-- profile header -->
<h1 class="heading" id="profile-un">Welcome {{ user.username }}</h1>
<div class="page-container">
    <p>package</p>

<div class="profile-page">
    <div class="profile-wrapper">
        <div class="circle-container top">
        </div>
        <div class="profile-info">
            <h2 id="profile-name">{{ user.first_name }}&nbsp;{{ user.last_name }}</h2>
            <h3 id="profile-email">{{ user.email }}</h3>
        </div>
    </div>
    <hr class="hr-body"/>

    <!-- my shipments block -->
    <h2 class="heading">MY SHIPMENTS</h2>
    <div id="avail_del">
        <h2>Packages for Delivery</h2>

        {% for p in packages %}
        <div class="shipments">
            <div class="section-1">
                <h5 class="sec-1 st">SHIPPING FROM</h5>
                <h4 class="sec-1 un">{{ p.origination }}</h4>
            </div>
            <div class="section-2">
                <div class="cities">
                    <div class="circle-container body1">
                        <!-- city first letter -->
                        A
                    </div>
                    <div class="city">
                        <!-- city -->
                        POINT A
                    </div>
                </div>
    
                <div class="dots">● &nbsp; ● &nbsp; ● &nbsp; ●</div>
                        <!-- distance -->
                        
                        <div class="distance"> 
                            {% if p.destination_length > 0 %}
                            <h2>{{ p.destination_length }} mi</h2> 
                            {% else %}
                            <h2>N/A</h2>
                            {% endif %}
                        </div>    
    
                <div class="dots">● &nbsp; ● &nbsp; ● &nbsp; ●</div>
    
                <div class="cities">
                    <div class="circle-container body2">
                        <!-- city first letter -->
                        B
                    </div>
                    <div class="city">
                        <!-- city -->
                        POINT B
                    </div>
                </div>
            </div>
            <div class="section-4">
                <h5 class="sec-4 st">DELIVER TO</h5>
                <h4 class="sec-4 un">{{ p.destination }}</h4>
            </div>
            <div class="section-3">
                <a class="package-button edit" href="{% url 'package_update' p.id %}">Edit</a>
                <a class="package-button delete" href="{% url 'package_delete' p.id %}">CANCEL</a>
            </div>
        </div>
        {% endfor %}
        <!-- pull info for created shipments -->
    </div>


{% endblock %}